# Generated by Django 3.0.8 on 2020-08-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
    ]
