# Generated by Django 3.0.8 on 2020-08-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
    ]
